---

examples:

  -
    title: "Line Charts"
    dir: "linecharts"
    examples:
      -
        title: "Simple line chart"
        file: "simple_lines"
        url: "/linecharts/simple_lines"
      -
        title: "Lines with points"
        file: "lines_with_points"
        url: "/linecharts/lines_with_points"
#      -
#        title: "Lines with points &amp; labels"
#        file: "lines_with_points"
#        url: "/linecharts/lines_with_points"
      -
        title: "Explicit range/domain"
        file: "explicit_domain"
        url: "/linecharts/explicit_domain"
#      -
#        title: "Lines with time domain"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Multiple Y Axes"
        file: "multiple_y_axes"
        url: "/linecharts/multiple_y_axes"
      -
        title: "Logarithmic domain"
        file: "logarithmic_domain"
        url: "/linecharts/logarithmic_domain"
#      -
#        title: "Line and Point styles"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Lines irregular intervals"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Lines with missing data"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Inverted Axis"
        file: "inverted_axis"
        url: "/linecharts/inverted_axis"
#  -
#    title: "Area Charts"
#    dir: "areacharts"
#    examples:
#      -
#        title: "Simple area chart"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Areas with borders/points"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Stacked areas"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Area ranges"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
  -
    title: "Bar Charts"
    dir: "barcharts"
    examples:
      -
        title: "Horizontal bar chart"
        file: "horizontal_bars"
        url: "/barcharts/horizontal_bars"
      -
        title: "Vertical bar chart, multiple series"
        file: "vertical_bars"
        url: "/barcharts/vertical_bars"
      -
        title: "Stacked Bar Chart"
        file: "stacked_bars"
        url: "/barcharts/stacked_bars"
#      -
#        title: "Bars with negative values"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Horizontal range bars"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Histogram"
#        file: "horizontal_bars"
#      -
#        title: "Bars with lines"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Bars with labels"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
##
#  -
#    title: "Axis &amp; Legend styles"
#    examples:
#  -
#    title: "Point/Bubble Charts"
#    dir: "barcharts"
#    examples:
#      -
#        title: "Simple point chart"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "3D bubble chart"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Multiple point series"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Points with labels"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Points with middle axis"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#
  -
    title: "Combined Charts"
    dir: "combined"
    examples:
      -
        title: "Bars and Lines"
        file: "bars_and_lines"
        url: "/combined/barsandlines"
#      -
#        title: "Lines with error bars"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Areas with lines"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#

#  -
#    title: "Custom styles"
#    dir: "styles"
#    examples:
#      -
#        title: "Legend styles"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Axis styles"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Default Style"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Dark Style"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#
#  -
#    title: "Dashboards"
#    dir: "dashboards"
#    examples:
#      -
#        title: "Web application"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"

#  * horizontal with labels outside
#  * horizontal with labels inside
#  * multiple y axis

sitemap:
  getting_started:
    title: "Using FnordMetric"
    pages:
      -
        title: "Installation"
        url: "/query_language/reference"
      -
        title: "Getting Started"
        url: "/query_language/reference"
      -
        title: "Commandline Interface"
        url: "/query_language/reference"
      -
        title: "Web Interface"
        url: "/query_language/reference"


  query_language:
    title: "Query Language"
    pages:
      -
        title: "Introduction"
        url: "/query_language/overview"
      -
        title: "Drawing Charts"
        url: "/query_language/reference"
      -
        title: "Defining Series"
        url: "/query_language/reference"
      -
        title: "Data Sources"
        url: "/query_language/reference"
      -
        title: "Time-based Aggregations"
        url: "/query_language/reference"
      -
        title: "Built-in Functions"
        url: "/query_language/reference"
      -
        title: "Syntax Reference"
        url: "/query_language/reference"
      -
        title: "Example Queries"
        url: "/query_language/reference"

  charts:
    title: "Custom Charts"
    pages:
      -
        title: "Axis styles"
        url: "/query_language/reference"
      -
        title: "Legend styles"
        url: "/query_language/reference"
      -
        title: "Point and Line styles"
        url: "/query_language/reference"
      -
        title: "Line Charts"
        url: "/query_language/reference"
      -
        title: "Point Charts"
        url: "/query_language/reference"
      -
        title: "Area Charts"
        url: "/query_language/reference"
      -
        title: "Bar Charts"
        url: "/query_language/reference"
      -
        title: "Combining Charts"
        url: "/query_language/reference"
      -
        title: "Timeseries Data"
        url: "/query_language/reference"
      -
        title: "Multiple Domains"
        url: "/query_language/reference"
      -
        title: "Interactive Charts"
        url: "/query_language/reference"
      -
        title: "Styles / Themes"
        url: "/query_language/reference"

  data_sources:
    title: "Data Sources"
    pages:
      -
        title: "Query from CSV"
        url: "/query_language/reference"
      -
        title: "Query from MySQL"
        url: "/query_language/reference"
      -
        title: "Query from statsd"
        url: "/query_language/reference"

  cpp_api:
    title: "C++ API"
    pages:
      -
        title: "Introduction"
        url: "/query_language/reference"
      -
        title: "API Reference"
        url: "/query_language/reference"
      -
        title: "Examples"
        url: "/query_language/reference"

  dashboards:
    title: "Building Dashboards"
    pages:
      -
        title: "Dashboards"
        url: "/query_language/reference"
      -
        title: "HTML5 API Reference"
        url: "/query_language/reference"
      -
        title: "Examples"
        url: "/query_language/reference"

  hacking:
    title: "Hacking"
    pages:
      -
        title: "Contributing"
        url: "/enterprise_api_reference"
      -
        title: "Old Documentation"
        url: "/enterprise_usage"

